# Generated by Django 3.1.3 on 2020-11-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201123_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='video',
            field=models.FilePathField(null=True),
        ),
    ]
